on: push
jobs:
        test:
                strategy:
                        matrix:
                                platform: [ubuntu-latest, macos-latest, windows-latest]
                run-on: ${{ matrix.platform }}
                steps:
                - uses: actions/checkout@master
                - run: go run .

